version: '3'

services:
  weather-companion:
    ports:
      - "8000:8000"
    build:
      context: ./../..
      dockerfile: environments/prod/Dockerfile
    environment:
      - WEATHER_CLIENT_API_KEY=cc803778f0556511257a09dc0789f825

